---
linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen

    - path: main\.go
      # Accept pprof is automatically exposed
      text: "G108:"

    - path: main\.go
      # Accept sha1 for signature
      text: "G505:"
