FROM alpine:latest
RUN apk --no-cache add ca-certificates
RUN mkdir -p /etc/svalinn
VOLUME /etc/svalinn
WORKDIR /root/
COPY svalinn.yaml .
COPY svalinn_linux_amd64 .
ENTRYPOINT ["./svalinn_linux_amd64"]
